-- Oracle 12c+
-- Baza podataka: SELEKCIJA KANDIDATA

CREATE TABLE OGLAS (
    OGLAS_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    NAZIV_POZICIJE VARCHAR2(200) NOT NULL,
    VRSTA_OGLASA VARCHAR2(20) NOT NULL,
    OPIS CLOB,
    ZAHTEVI CLOB,
    MIN_PLATA NUMBER(10,2),
    MAX_PLATA NUMBER(10,2),
    DATUM_OBJAVE DATE NOT NULL,
    DATUM_ZATVARANJA DATE,
    STATUS VARCHAR2(30) NOT NULL,

    CONSTRAINT PK_OGLAS PRIMARY KEY (OGLAS_ID),
    CONSTRAINT CHK_OGLAS_VRSTA CHECK (
        VRSTA_OGLASA IN ('STALNI', 'PRIVREMENI', 'PRAKSA', 'SEZONSKI')
    ),
    CONSTRAINT CHK_OGLAS_STATUS CHECK (
        STATUS IN ('AKTIVAN', 'ZATVOREN', 'U_PROCESU_SELEKCIJE')
    ),
    CONSTRAINT CHK_OGLAS_PLATE CHECK (
        (MIN_PLATA IS NULL OR MIN_PLATA >= 0) AND
        (MAX_PLATA IS NULL OR MAX_PLATA >= 0) AND
        (MIN_PLATA IS NULL OR MAX_PLATA IS NULL OR MIN_PLATA <= MAX_PLATA)
    ),
    CONSTRAINT CHK_OGLAS_DATUMI CHECK (
        DATUM_ZATVARANJA IS NULL OR DATUM_ZATVARANJA >= DATUM_OBJAVE
    )
);

CREATE TABLE OGLAS_PRIVREMENI (
    OGLAS_ID NUMBER NOT NULL,
    PROJEKAT VARCHAR2(300) NOT NULL,
    DATUM_POCETKA DATE NOT NULL,
    DATUM_ZAVRSETKA DATE NOT NULL,

    CONSTRAINT PK_OGLAS_PRIVREMENI PRIMARY KEY (OGLAS_ID),
    CONSTRAINT FK_PRIVREMENI_OGLAS FOREIGN KEY (OGLAS_ID)
        REFERENCES OGLAS (OGLAS_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_PRIVREMENI_DATUMI CHECK (
        DATUM_ZAVRSETKA >= DATUM_POCETKA
    )
);

CREATE TABLE OGLAS_PRAKSA (
    OGLAS_ID NUMBER NOT NULL,
    MENTOR_IME VARCHAR2(100) NOT NULL,
    MENTOR_PREZIME VARCHAR2(100) NOT NULL,
    DUZINA_TRAJANJA NUMBER(3) NOT NULL,

    CONSTRAINT PK_OGLAS_PRAKSA PRIMARY KEY (OGLAS_ID),
    CONSTRAINT FK_PRAKSA_OGLAS FOREIGN KEY (OGLAS_ID)
        REFERENCES OGLAS (OGLAS_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_PRAKSA_TRAJANJE CHECK (DUZINA_TRAJANJA > 0)
);

CREATE TABLE OGLAS_SEZONSKI (
    OGLAS_ID NUMBER NOT NULL,
    SEZONA VARCHAR2(100) NOT NULL,
    LOKACIJA VARCHAR2(200) NOT NULL,

    CONSTRAINT PK_OGLAS_SEZONSKI PRIMARY KEY (OGLAS_ID),
    CONSTRAINT FK_SEZONSKI_OGLAS FOREIGN KEY (OGLAS_ID)
        REFERENCES OGLAS (OGLAS_ID) ON DELETE CASCADE
);

CREATE TABLE CV (
    CV_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    DATUM_PODNOSENJA DATE NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    IME VARCHAR2(100) NOT NULL,
    PREZIME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    TELEFON VARCHAR2(30) NOT NULL,
    OGLAS_ID NUMBER NOT NULL,

    CONSTRAINT PK_CV PRIMARY KEY (CV_ID),
    CONSTRAINT FK_CV_OGLAS FOREIGN KEY (OGLAS_ID)
        REFERENCES OGLAS (OGLAS_ID),
    CONSTRAINT UQ_CV_EMAIL_OGLAS UNIQUE (EMAIL, OGLAS_ID),
    CONSTRAINT CHK_CV_STATUS CHECK (
        STATUS IN ('PRIMLJEN', 'U_PROCESU', 'ODBIJEN', 'POZVAN_NA_INTERVJU')
    )
);

CREATE TABLE INTERVJU (
    INTERVJU_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    DATUM DATE NOT NULL,
    VREME TIMESTAMP NOT NULL,
    TIP_INTERVJUA VARCHAR2(20) NOT NULL,
    LOKACIJA VARCHAR2(300) NOT NULL,
    ZAPOSLENI_IME VARCHAR2(100) NOT NULL,
    ZAPOSLENI_PREZIME VARCHAR2(100) NOT NULL,
    OCENA NUMBER(2) NOT NULL,
    NAPOMENE CLOB,
    CV_ID NUMBER NOT NULL,

    CONSTRAINT PK_INTERVJU PRIMARY KEY (INTERVJU_ID),
    CONSTRAINT FK_INTERVJU_CV FOREIGN KEY (CV_ID)
        REFERENCES CV (CV_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_INTERVJU_TIP CHECK (
        TIP_INTERVJUA IN ('LICNI', 'VIDEO', 'TELEFONSKI')
    ),
    CONSTRAINT CHK_INTERVJU_VREME CHECK (
        REGEXP_LIKE(VREME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')
    ),
    CONSTRAINT CHK_INTERVJU_OCENA CHECK (OCENA BETWEEN 1 AND 10)
);

CREATE TABLE TEST (
    TEST_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    REZULTAT NUMBER(5,2) NOT NULL,
    DATUM_TESTIRANJA DATE NOT NULL,
    VRSTA_TESTIRANJA VARCHAR2(100) NOT NULL,
    KOMENTAR CLOB,
    CV_ID NUMBER NOT NULL,

    CONSTRAINT PK_TEST PRIMARY KEY (TEST_ID),
    CONSTRAINT FK_TEST_CV FOREIGN KEY (CV_ID)
        REFERENCES CV (CV_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_TEST_REZULTAT CHECK (REZULTAT BETWEEN 0 AND 100)
);

CREATE TABLE ODLUKA (
    ODLUKA_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    STATUS VARCHAR2(30) NOT NULL,
    DATUM_DONOSENJA_ODLUKE DATE NOT NULL,
    PONUDJENA_PLATA NUMBER(10,2),
    PRIHVATIO_PONUDU NUMBER(1) NOT NULL,
    DATUM_POCETKA_RADA DATE,
    RAZLOG_ODBIJANJA CLOB,
    CV_ID NUMBER NOT NULL,

    CONSTRAINT PK_ODLUKA PRIMARY KEY (ODLUKA_ID),
    CONSTRAINT UQ_ODLUKA_CV UNIQUE (CV_ID),
    CONSTRAINT FK_ODLUKA_CV FOREIGN KEY (CV_ID)
        REFERENCES CV (CV_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_ODLUKA_STATUS CHECK (
        STATUS IN ('IZABRAN', 'ODBIJEN', 'REZERVA', 'NA_CEKANJU')
    ),
    CONSTRAINT CHK_ODLUKA_PLATA CHECK (
        PONUDJENA_PLATA IS NULL OR PONUDJENA_PLATA >= 0
    ),
    CONSTRAINT CHK_ODLUKA_PRIHVATIO CHECK (
        PRIHVATIO_PONUDU IN (0, 1)
    ),
    CONSTRAINT CHK_ODLUKA_POCETAK CHECK (
        PRIHVATIO_PONUDU = 0 OR DATUM_POCETKA_RADA IS NOT NULL
    ),
    CONSTRAINT CHK_ODLUKA_ODBIJANJE CHECK (
        STATUS <> 'ODBIJEN' OR RAZLOG_ODBIJANJA IS NOT NULL
    )
);

CREATE INDEX IDX_CV_OGLAS_ID ON CV (OGLAS_ID);
CREATE INDEX IDX_INTERVJU_CV_ID ON INTERVJU (CV_ID);
CREATE INDEX IDX_TEST_CV_ID ON TEST (CV_ID);
CREATE INDEX IDX_OGLAS_STATUS ON OGLAS (STATUS);

