-- Pokrenuti nakon 01_Kreiranje_baze_Oracle.sql
-- ID vrednosti generise Oracle; ne unose se rucno

INSERT INTO OGLAS (NAZIV_POZICIJE, VRSTA_OGLASA, OPIS, ZAHTEVI,
MIN_PLATA, MAX_PLATA, DATUM_OBJAVE, DATUM_ZATVARANJA, STATUS)
VALUES ('Java Backend Developer', 'STALNI',
'Razvoj i odrzavanje Java serverskih aplikacija.',
'Java, Spring Boot, SQL i REST servisi.',
120000, 180000, DATE '2026-05-01', DATE '2026-05-31', 'AKTIVAN');

INSERT INTO OGLAS (NAZIV_POZICIJE, VRSTA_OGLASA, OPIS, ZAHTEVI,
MIN_PLATA, MAX_PLATA, DATUM_OBJAVE, DATUM_ZATVARANJA, STATUS)
VALUES ('Project Manager', 'PRIVREMENI',
'Vodjenje projekta migracije ERP sistema.',
'Iskustvo u vodjenju projekata i Agile metodologiji.',
150000, 210000, DATE '2026-05-02', DATE '2026-06-15', 'AKTIVAN');

INSERT INTO OGLAS (NAZIV_POZICIJE, VRSTA_OGLASA, OPIS, ZAHTEVI,
MIN_PLATA, MAX_PLATA, DATUM_OBJAVE, DATUM_ZATVARANJA, STATUS)
VALUES ('QA Intern', 'PRAKSA',
'Strucna praksa u timu za testiranje softvera.',
'Osnove testiranja softvera i SQL-a.',
40000, 60000, DATE '2026-05-03', DATE '2026-06-10', 'AKTIVAN');

INSERT INTO OGLAS (NAZIV_POZICIJE, VRSTA_OGLASA, OPIS, ZAHTEVI,
MIN_PLATA, MAX_PLATA, DATUM_OBJAVE, DATUM_ZATVARANJA, STATUS)
VALUES ('Spasilac na bazenu', 'SEZONSKI',
'Sezonski rad na otvorenom bazenu.',
'Sertifikat za spasioca i dobra fizicka spremnost.',
70000, 90000, DATE '2026-05-04', DATE '2026-06-20', 'AKTIVAN');

INSERT INTO OGLAS_PRIVREMENI (OGLAS_ID, PROJEKAT, PERIOD_ANGAZOVANJA)
SELECT OGLAS_ID, 'Migracija ERP sistema', '6 meseci'
FROM OGLAS
WHERE NAZIV_POZICIJE = 'Project Manager' AND VRSTA_OGLASA = 'PRIVREMENI';

INSERT INTO OGLAS_PRAKSA (OGLAS_ID, MENTOR_IME, MENTOR_PREZIME, DUZINA_TRAJANJA)
SELECT OGLAS_ID, 'Marko', 'Markovic', 3
FROM OGLAS
WHERE NAZIV_POZICIJE = 'QA Intern' AND VRSTA_OGLASA = 'PRAKSA';

INSERT INTO OGLAS_SEZONSKI (OGLAS_ID, SEZONA, LOKACIJA)
SELECT OGLAS_ID, 'Leto 2026', 'Budva'
FROM OGLAS
WHERE NAZIV_POZICIJE = 'Spasilac na bazenu' AND VRSTA_OGLASA = 'SEZONSKI';

INSERT INTO CV (DATUM_PODNOSENJA, STATUS, IME, PREZIME, EMAIL, TELEFON, OGLAS_ID)
SELECT DATE '2026-05-10', 'U_PROCESU', 'Petar', 'Petrovic',
'petar.petrovic@gmail.com', '061111111', OGLAS_ID
FROM OGLAS
WHERE NAZIV_POZICIJE = 'Java Backend Developer' AND VRSTA_OGLASA = 'STALNI';

INSERT INTO CV (DATUM_PODNOSENJA, STATUS, IME, PREZIME, EMAIL, TELEFON, OGLAS_ID)
SELECT DATE '2026-05-11', 'POZVAN_NA_INTERVJU', 'Nikola', 'Nikolic',
'nikola.nikolic@gmail.com', '062222222', OGLAS_ID
FROM OGLAS
WHERE NAZIV_POZICIJE = 'Project Manager' AND VRSTA_OGLASA = 'PRIVREMENI';

INSERT INTO CV (DATUM_PODNOSENJA, STATUS, IME, PREZIME, EMAIL, TELEFON, OGLAS_ID)
SELECT DATE '2026-05-12', 'U_PROCESU', 'Ana', 'Jovanovic',
'ana.jovanovic@gmail.com', NULL, OGLAS_ID
FROM OGLAS
WHERE NAZIV_POZICIJE = 'QA Intern' AND VRSTA_OGLASA = 'PRAKSA';

INSERT INTO INTERVJU (DATUM, VREME, TIP, LOKACIJA, ZAPOSLENI_IME,
ZAPOSLENI_PREZIME, OCENA, NAPOMENE, CV_ID)
SELECT DATE '2026-05-20', '12:00', 'VIDEO', 'Microsoft Teams',
'Jovan', 'Jovanovic', 9, 'Kandidat je pokazao dobro tehnicko znanje.', CV_ID
FROM CV WHERE EMAIL = 'petar.petrovic@gmail.com';

INSERT INTO INTERVJU (DATUM, VREME, TIP, LOKACIJA, ZAPOSLENI_IME,
ZAPOSLENI_PREZIME, OCENA, NAPOMENE, CV_ID)
SELECT DATE '2026-05-22', '10:30', 'UZIVO', 'Sala 2',
'Milica', 'Milic', 8, 'Kandidat ima iskustvo u vodjenju projekata.', CV_ID
FROM CV WHERE EMAIL = 'nikola.nikolic@gmail.com';

INSERT INTO TEST (REZULTAT, DATUM_TESTIRANJA, VRSTA_TESTIRANJA, KOMENTAR, CV_ID)
SELECT 87.50, DATE '2026-05-18', 'Tehnicki test',
'Veoma dobar rezultat.', CV_ID
FROM CV WHERE EMAIL = 'petar.petrovic@gmail.com';

INSERT INTO TEST (REZULTAT, DATUM_TESTIRANJA, VRSTA_TESTIRANJA, KOMENTAR, CV_ID)
SELECT 92.00, DATE '2026-05-19', 'Test upravljanja projektima',
'Odlican rezultat.', CV_ID
FROM CV WHERE EMAIL = 'nikola.nikolic@gmail.com';

INSERT INTO ODLUKA (STATUS, DATUM_DONOSENJA_ODLUKE, PONUDJENA_PLATA,
PRIHVATIO_PONUDU, DATUM_POCETKA_RADA, RAZLOG_ODBIJANJA, CV_ID)
SELECT 'IZABRAN', DATE '2026-05-25', 170000, 'D', DATE '2026-06-15', NULL, CV_ID
FROM CV WHERE EMAIL = 'petar.petrovic@gmail.com';

INSERT INTO ODLUKA (STATUS, DATUM_DONOSENJA_ODLUKE, PONUDJENA_PLATA,
PRIHVATIO_PONUDU, DATUM_POCETKA_RADA, RAZLOG_ODBIJANJA, CV_ID)
SELECT 'ODBIJEN', DATE '2026-05-26', NULL, NULL, NULL,
'Odabran je kandidat sa vise relevantnog iskustva.', CV_ID
FROM CV WHERE EMAIL = 'nikola.nikolic@gmail.com';

COMMIT;
