--------------------------------------------------------
--  File created - utorak-maj-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CV_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "S19751"."CV_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence INTERVJU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "S19751"."INTERVJU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence ODLUKA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "S19751"."ODLUKA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence OGLAS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "S19751"."OGLAS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence TEST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "S19751"."TEST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Table CV
--------------------------------------------------------

  CREATE TABLE "S19751"."CV" 
   (	"CV_ID" NUMBER, 
	"OGLAS_ID" NUMBER, 
	"IME" VARCHAR2(100 BYTE), 
	"PREZIME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"TELEFON" VARCHAR2(30 BYTE), 
	"DATUM_PODNOSENJA" DATE, 
	"STATUS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
--------------------------------------------------------
--  DDL for Table INTERVJU
--------------------------------------------------------

  CREATE TABLE "S19751"."INTERVJU" 
   (	"INTERVJU_ID" NUMBER, 
	"CV_ID" NUMBER, 
	"DATUM_INTERVJUA" DATE, 
	"VREME_INTERVJUA" VARCHAR2(5 BYTE), 
	"TIP_INTERVJUA" VARCHAR2(20 BYTE), 
	"LOKACIJA" VARCHAR2(300 BYTE), 
	"IME_ZAPOSLENOG" VARCHAR2(100 BYTE), 
	"PREZIME_ZAPOSLENOG" VARCHAR2(100 BYTE), 
	"OCENA" NUMBER(2,0), 
	"NAPOMENE" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" 
 LOB ("NAPOMENE") STORE AS SECUREFILE (
  TABLESPACE "STUDENTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ODLUKA
--------------------------------------------------------

  CREATE TABLE "S19751"."ODLUKA" 
   (	"ODLUKA_ID" NUMBER, 
	"CV_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"DATUM_DONOSENJA_ODLUKE" DATE, 
	"PONUDJENA_PLATA" NUMBER(10,2), 
	"PRIHVATANJE_PONUDE" CHAR(1 BYTE), 
	"DATUM_POCETKA_RADA" DATE, 
	"RAZLOG_ODBIJANJA" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
--------------------------------------------------------
--  DDL for Table OGLAS
--------------------------------------------------------

  CREATE TABLE "S19751"."OGLAS" 
   (	"OGLAS_ID" NUMBER, 
	"NAZIV_POZICIJE" VARCHAR2(200 BYTE), 
	"VRSTA_OGLASA" VARCHAR2(20 BYTE), 
	"OPIS" CLOB, 
	"ZAHTEVI" CLOB, 
	"MIN_PLATA" NUMBER(10,2), 
	"MAX_PLATA" NUMBER(10,2), 
	"DATUM_OBJAVE" DATE, 
	"DATUM_ZATVARANJA" DATE, 
	"STATUS" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" 
 LOB ("OPIS") STORE AS SECUREFILE (
  TABLESPACE "STUDENTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ZAHTEVI") STORE AS SECUREFILE (
  TABLESPACE "STUDENTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table OGLAS_PRAKSA
--------------------------------------------------------

  CREATE TABLE "S19751"."OGLAS_PRAKSA" 
   (	"OGLAS_ID" NUMBER, 
	"IME_ZAPOSLENOG" VARCHAR2(100 BYTE), 
	"PREZIME_ZAPOSLENOG" VARCHAR2(100 BYTE), 
	"DUZINA_TRAJANJA" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
--------------------------------------------------------
--  DDL for Table OGLAS_PRIVREMENI
--------------------------------------------------------

  CREATE TABLE "S19751"."OGLAS_PRIVREMENI" 
   (	"OGLAS_ID" NUMBER, 
	"PROJEKAT" VARCHAR2(300 BYTE), 
	"PERIOD_ANGAZOVANJA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
--------------------------------------------------------
--  DDL for Table OGLAS_SEZONSKI
--------------------------------------------------------

  CREATE TABLE "S19751"."OGLAS_SEZONSKI" 
   (	"OGLAS_ID" NUMBER, 
	"SEZONA" VARCHAR2(100 BYTE), 
	"LOKACIJA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "S19751"."TEST" 
   (	"TEST_ID" NUMBER, 
	"CV_ID" NUMBER, 
	"REZULTAT" NUMBER(5,2), 
	"DATUM_TESTIRANJA" DATE, 
	"VRSTA_TESTIRANJA" VARCHAR2(100 BYTE), 
	"KOMENTAR" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS" 
 LOB ("KOMENTAR") STORE AS SECUREFILE (
  TABLESPACE "STUDENTS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into S19751.CV
SET DEFINE OFF;
Insert into S19751.CV (CV_ID,OGLAS_ID,IME,PREZIME,EMAIL,TELEFON,DATUM_PODNOSENJA,STATUS) values (1,1,'Petar','Petrovic','petar@gmail.com','061111111',to_date('26-MAY-26','DD-MON-RR'),'U_PROCESU');
Insert into S19751.CV (CV_ID,OGLAS_ID,IME,PREZIME,EMAIL,TELEFON,DATUM_PODNOSENJA,STATUS) values (2,2,'Nikola','Nikolic','nikola@gmail.com','062222222',to_date('26-MAY-26','DD-MON-RR'),'PRIMLJEN');
REM INSERTING into S19751.INTERVJU
SET DEFINE OFF;
Insert into S19751.INTERVJU (INTERVJU_ID,CV_ID,DATUM_INTERVJUA,VREME_INTERVJUA,TIP_INTERVJUA,LOKACIJA,IME_ZAPOSLENOG,PREZIME_ZAPOSLENOG,OCENA) values (1,1,to_date('31-MAY-26','DD-MON-RR'),'12:00','VIDEO','Microsoft Teams','Jovan','Jovanovic',9);
REM INSERTING into S19751.ODLUKA
SET DEFINE OFF;
Insert into S19751.ODLUKA (ODLUKA_ID,CV_ID,STATUS,DATUM_DONOSENJA_ODLUKE,PONUDJENA_PLATA,PRIHVATANJE_PONUDE,DATUM_POCETKA_RADA,RAZLOG_ODBIJANJA) values (1,1,'IZABRAN',to_date('02-JUN-26','DD-MON-RR'),180000,'D',to_date('25-JUN-26','DD-MON-RR'),null);
REM INSERTING into S19751.OGLAS
SET DEFINE OFF;
Insert into S19751.OGLAS (OGLAS_ID,NAZIV_POZICIJE,VRSTA_OGLASA,MIN_PLATA,MAX_PLATA,DATUM_OBJAVE,DATUM_ZATVARANJA,STATUS) values (1,'Web Developer','PRIVREMENI',100000,200000,to_date('26-MAY-26','DD-MON-RR'),to_date('25-JUN-26','DD-MON-RR'),'AKTIVAN');
Insert into S19751.OGLAS (OGLAS_ID,NAZIV_POZICIJE,VRSTA_OGLASA,MIN_PLATA,MAX_PLATA,DATUM_OBJAVE,DATUM_ZATVARANJA,STATUS) values (2,'QA Intern','PRAKSA',40000,60000,to_date('26-MAY-26','DD-MON-RR'),to_date('15-JUN-26','DD-MON-RR'),'AKTIVAN');
Insert into S19751.OGLAS (OGLAS_ID,NAZIV_POZICIJE,VRSTA_OGLASA,MIN_PLATA,MAX_PLATA,DATUM_OBJAVE,DATUM_ZATVARANJA,STATUS) values (3,'Spasilac na bazenu','SEZONSKI',70000,90000,to_date('26-MAY-26','DD-MON-RR'),to_date('25-JUL-26','DD-MON-RR'),'AKTIVAN');
Insert into S19751.OGLAS (OGLAS_ID,NAZIV_POZICIJE,VRSTA_OGLASA,MIN_PLATA,MAX_PLATA,DATUM_OBJAVE,DATUM_ZATVARANJA,STATUS) values (4,'Web developer','PRIVREMENI',100000,210000,to_date('26-MAY-26','DD-MON-RR'),null,'AKTIVAN');
REM INSERTING into S19751.OGLAS_PRAKSA
SET DEFINE OFF;
Insert into S19751.OGLAS_PRAKSA (OGLAS_ID,IME_ZAPOSLENOG,PREZIME_ZAPOSLENOG,DUZINA_TRAJANJA) values (2,'Marko','Markovic',3);
REM INSERTING into S19751.OGLAS_PRIVREMENI
SET DEFINE OFF;
Insert into S19751.OGLAS_PRIVREMENI (OGLAS_ID,PROJEKAT,PERIOD_ANGAZOVANJA) values (1,'Migracija ERP sistema','6 meseci');
REM INSERTING into S19751.OGLAS_SEZONSKI
SET DEFINE OFF;
Insert into S19751.OGLAS_SEZONSKI (OGLAS_ID,SEZONA,LOKACIJA) values (3,'Leto 2026','Budva');
REM INSERTING into S19751.TEST
SET DEFINE OFF;
Insert into S19751.TEST (TEST_ID,CV_ID,REZULTAT,DATUM_TESTIRANJA,VRSTA_TESTIRANJA) values (1,1,87.5,to_date('28-MAY-26','DD-MON-RR'),'Tehnicki test');
--------------------------------------------------------
--  Constraints for Table CV
--------------------------------------------------------

  ALTER TABLE "S19751"."CV" MODIFY ("OGLAS_ID" NOT NULL ENABLE);
  ALTER TABLE "S19751"."CV" MODIFY ("IME" NOT NULL ENABLE);
  ALTER TABLE "S19751"."CV" MODIFY ("PREZIME" NOT NULL ENABLE);
  ALTER TABLE "S19751"."CV" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "S19751"."CV" MODIFY ("DATUM_PODNOSENJA" NOT NULL ENABLE);
  ALTER TABLE "S19751"."CV" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "S19751"."CV" ADD PRIMARY KEY ("CV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OGLAS
--------------------------------------------------------

  ALTER TABLE "S19751"."OGLAS" MODIFY ("NAZIV_POZICIJE" NOT NULL ENABLE);
  ALTER TABLE "S19751"."OGLAS" MODIFY ("VRSTA_OGLASA" NOT NULL ENABLE);
  ALTER TABLE "S19751"."OGLAS" MODIFY ("DATUM_OBJAVE" NOT NULL ENABLE);
  ALTER TABLE "S19751"."OGLAS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "S19751"."OGLAS" ADD PRIMARY KEY ("OGLAS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OGLAS_PRAKSA
--------------------------------------------------------

  ALTER TABLE "S19751"."OGLAS_PRAKSA" ADD CONSTRAINT "CHK_PRAKSA_DUZINA" CHECK (DUZINA_TRAJANJA > 0) ENABLE;
  ALTER TABLE "S19751"."OGLAS_PRAKSA" MODIFY ("IME_ZAPOSLENOG" NOT NULL ENABLE);
  ALTER TABLE "S19751"."OGLAS_PRAKSA" MODIFY ("PREZIME_ZAPOSLENOG" NOT NULL ENABLE);
  ALTER TABLE "S19751"."OGLAS_PRAKSA" MODIFY ("DUZINA_TRAJANJA" NOT NULL ENABLE);
  ALTER TABLE "S19751"."OGLAS_PRAKSA" ADD PRIMARY KEY ("OGLAS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OGLAS_PRIVREMENI
--------------------------------------------------------

  ALTER TABLE "S19751"."OGLAS_PRIVREMENI" MODIFY ("PROJEKAT" NOT NULL ENABLE);
  ALTER TABLE "S19751"."OGLAS_PRIVREMENI" MODIFY ("PERIOD_ANGAZOVANJA" NOT NULL ENABLE);
  ALTER TABLE "S19751"."OGLAS_PRIVREMENI" ADD PRIMARY KEY ("OGLAS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INTERVJU
--------------------------------------------------------

  ALTER TABLE "S19751"."INTERVJU" MODIFY ("CV_ID" NOT NULL ENABLE);
  ALTER TABLE "S19751"."INTERVJU" MODIFY ("DATUM_INTERVJUA" NOT NULL ENABLE);
  ALTER TABLE "S19751"."INTERVJU" MODIFY ("VREME_INTERVJUA" NOT NULL ENABLE);
  ALTER TABLE "S19751"."INTERVJU" MODIFY ("TIP_INTERVJUA" NOT NULL ENABLE);
  ALTER TABLE "S19751"."INTERVJU" MODIFY ("IME_ZAPOSLENOG" NOT NULL ENABLE);
  ALTER TABLE "S19751"."INTERVJU" MODIFY ("PREZIME_ZAPOSLENOG" NOT NULL ENABLE);
  ALTER TABLE "S19751"."INTERVJU" ADD PRIMARY KEY ("INTERVJU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "S19751"."TEST" MODIFY ("CV_ID" NOT NULL ENABLE);
  ALTER TABLE "S19751"."TEST" MODIFY ("DATUM_TESTIRANJA" NOT NULL ENABLE);
  ALTER TABLE "S19751"."TEST" MODIFY ("VRSTA_TESTIRANJA" NOT NULL ENABLE);
  ALTER TABLE "S19751"."TEST" ADD PRIMARY KEY ("TEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ODLUKA
--------------------------------------------------------

  ALTER TABLE "S19751"."ODLUKA" MODIFY ("CV_ID" NOT NULL ENABLE);
  ALTER TABLE "S19751"."ODLUKA" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "S19751"."ODLUKA" MODIFY ("DATUM_DONOSENJA_ODLUKE" NOT NULL ENABLE);
  ALTER TABLE "S19751"."ODLUKA" ADD PRIMARY KEY ("ODLUKA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
  ALTER TABLE "S19751"."ODLUKA" ADD UNIQUE ("CV_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OGLAS_SEZONSKI
--------------------------------------------------------

  ALTER TABLE "S19751"."OGLAS_SEZONSKI" MODIFY ("SEZONA" NOT NULL ENABLE);
  ALTER TABLE "S19751"."OGLAS_SEZONSKI" MODIFY ("LOKACIJA" NOT NULL ENABLE);
  ALTER TABLE "S19751"."OGLAS_SEZONSKI" ADD PRIMARY KEY ("OGLAS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "STUDENTS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CV
--------------------------------------------------------

  ALTER TABLE "S19751"."CV" ADD CONSTRAINT "FK_CV_OGLAS" FOREIGN KEY ("OGLAS_ID")
	  REFERENCES "S19751"."OGLAS" ("OGLAS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INTERVJU
--------------------------------------------------------

  ALTER TABLE "S19751"."INTERVJU" ADD CONSTRAINT "FK_INTERVJU_CV" FOREIGN KEY ("CV_ID")
	  REFERENCES "S19751"."CV" ("CV_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ODLUKA
--------------------------------------------------------

  ALTER TABLE "S19751"."ODLUKA" ADD CONSTRAINT "FK_ODLUKA_CV" FOREIGN KEY ("CV_ID")
	  REFERENCES "S19751"."CV" ("CV_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OGLAS_PRAKSA
--------------------------------------------------------

  ALTER TABLE "S19751"."OGLAS_PRAKSA" ADD CONSTRAINT "FK_PRAKSA_OGLAS" FOREIGN KEY ("OGLAS_ID")
	  REFERENCES "S19751"."OGLAS" ("OGLAS_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OGLAS_PRIVREMENI
--------------------------------------------------------

  ALTER TABLE "S19751"."OGLAS_PRIVREMENI" ADD CONSTRAINT "FK_PRIVREMENI_OGLAS" FOREIGN KEY ("OGLAS_ID")
	  REFERENCES "S19751"."OGLAS" ("OGLAS_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OGLAS_SEZONSKI
--------------------------------------------------------

  ALTER TABLE "S19751"."OGLAS_SEZONSKI" ADD CONSTRAINT "FK_SEZONSKI_OGLAS" FOREIGN KEY ("OGLAS_ID")
	  REFERENCES "S19751"."OGLAS" ("OGLAS_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "S19751"."TEST" ADD CONSTRAINT "FK_TEST_CV" FOREIGN KEY ("CV_ID")
	  REFERENCES "S19751"."CV" ("CV_ID") ON DELETE CASCADE ENABLE;
